<?php

namespace Pashedu\CompanyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeRepository extends EntityRepository
{
}
